version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- pwsh: >-
    $ver = "1.0." + $($env:APPVEYOR_BUILD_NUMBER)

    nuget pack IntelliTect.Coalesce.KnockoutJS.Template.nuspec -Version $ver
test: off
deploy: off