version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
install:
- cmd: nuget pack IntelliTect.Coalesce.KnockoutJS.Template.nuspec -Version 1.0.{APPVEYOR_BUILD_NUMBER}
build: off
test: off
deploy: off