version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
build_script:
- pwsh: nuget pack IntelliTect.Coalesce.KnockoutJS.Template.nuspec -Version $env:APPVEYOR_REPO_TAG_NAME
test: off
deploy: off