version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- pwsh: nuget pack IntelliTect.Coalesce.KnockoutJS.Template.nuspec -Version $env:APPVEYOR_BUILD_NUMBER
test: off
deploy: off